# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
warnings_are_errors: false

#apt_packages:
# - libgmp3-dev
# - libmpfr-dev

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_binary_packages:
 - rgdal
 - Rcpp
 - raster
 - maptools
 - testthat
 - covr
 - RColorBrewer
 - TeachingDemos
 - maps
 - sp
 - plyr
 - pracma

#r_github_packages:
 #- abarbour/kelvin

notifications:
 email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'