# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false
sudo: required

r_binary_packages:
  - rgdal

notifications:
 email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'